login/urls.py
from django.urls import path
from login.views import Login, CrearUsuario
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_view


app_name = "login"

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('Registrar/', CrearUsuario.as_view(), name='registrar'),
    path('logout/', login_required(auth_view.LogoutView.as_view(template_name="login:login")), name='logout')
]

product/urls.py
from django.contrib.auth import logout
from django.urls import path
from product.views import CreateProductoView, Listar, Eliminar, Actualizar, Ver, Inicio, Descargar
from django.contrib.auth.decorators import login_required

app_name = "product"

urlpatterns = [
    path('CrearProductos/', login_required(CreateProductoView.as_view()), name='CrearProductos'),
    path('ListarProductos/', login_required(Listar.as_view()), name='ListarProductos'),
    path('EliminarProducto/<int:pk>/', login_required(Eliminar.as_view()), name='EliminarProducto'),
    path('ActualizarProducto/<int:pk>', login_required(Actualizar.as_view()), name="ActulizarProducto"),
    path('VerProducto/<int:pk>/', login_required(Ver.as_view()), name='VerProducto'),
    path('Descargar/', login_required(Descargar.as_view()), name='Descargar'),
    path('', Inicio.as_view(), name='inicio'),
]

tineda/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls.conf import re_path
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login.urls')),
    path('', include('product.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth import models
from django.forms import widgets
import unicodedata
from django.utils.text import capfirst
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)

UserModel = get_user_model()


#
class UserCreation(UserCreationForm):
    """class for the form create a user"""


    password1 = forms.CharField(
        min_length=10,
        label=_("Password"),
        strip=False,
        widget=forms.TextInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'Contraseña'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        min_length=10,
        label=_("Password confirmation"),
        widget=forms.TextInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'Confirmar Contraseña'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)


    """Meta class, which is responsible for loading the model you want to use
      and the fields you want to use for the form """
    class Meta:
        model = User
        
        fields = [
            'username',
            'first_name',
            'last_name',
            'email'
        ]
        labels ={
            'username': 'username',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
        }
        widgets = {
            'email':forms.TextInput(attrs={'class':'form-control','id':'field-5', 'placeholder':'email'}),
        }


class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    username = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
    )

    error_messages = {
        'invalid_login': _(
            "Por favor ingrese un nombre de usuario y una contraseña conrrecta. Recuerde que los campos son sensibles a las mayúsculas."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the label for the "username" field.
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        return username
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache

login/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, CreateView, TemplateView
from django.views.generic import View
from .forms import UserCreation, AuthenticationForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
# Create your views here.

#here the logic for the system functionality will be applied

"""Class to create a user"""
class CrearUsuario(CreateView):
	#We indicate that the model that we are going to use is the model that django offers
    model = User
	#We indicate that the form to use is the form that we have created in forms.py
    form_class = UserCreation
	#We establish the template to use
    template_name = "registrar.html"
	#We tell you that when the operation has been successfully completed redirect us to the url where you can log in
    success_url = reverse_lazy("login:login")



"""class that is responsible for user authentication to login"""
class Login(FormView):
	#We establish the template to use
	template_name = 'login.html'
	#We indicate that the form to use is the Django authentication form
	form_class = AuthenticationForm
	#We tell you that when the operation has been successfully completed redirect us to the start url of the application
	success_url =  reverse_lazy("product:ListarProductos")

	def form_valid(self, form):
		login(self.request, form.get_user())
		return super(Login, self).form_valid(form)

templates/ActualizarProducto.html
<!--is responsible for bringing the template base.html which contains the top bar of the page-->
{% include 'base.html' %}


<!--the fields form." " are the fields of the forms previously created in the forms.py-->

<!---This template is in charge of updating the product data-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="select" style="display: none;">
        {{form.usuario}}
    </div>
    
    <header class="header">
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Nombre del producto:</label>
            {{form.nombreProduct}}
        </div>
        <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Precio:</label>
            {{form.precio}}
        </div>
        <div class="form-floating">
            <p>informacion:</p>
            {{form.informacion}}
        </div>
        <br>
        <div class="form-group row">
            <label for="example-date-input" class="col-2 col-form-label">Date</label>
            <div class="col-10">
                {{form.fecha_adquisicion}}
            </div>
        </div>
        <br>
        <div class="mb-3">
        <label for="formFile" class="form-label">Imagen:</label>
            {{form.imagen}}
        </div>
        <input type="submit" value="enviar" class="btn btn-primary">
    </header>

</form>

templates/CrearProducto.html
<!--is responsible for bringing the template base.html which contains the top bar of the page-->
{% include 'base.html' %}

<!--the fields form." " are the fields of the forms previously created in the forms.py-->
<!--form to create a user-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{from.errors}}
    <header class="header">     
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Nombre del producto</label>
            <input type="text" class="form-control" name="producto" id="formGroupExampleInput" placeholder="Example input placeholder">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Preciol</label>
            <input type="text" class="form-control" name="precio" id="formGroupExampleInput2" placeholder="Another input placeholder">
          </div>
        <div class="form-floating">
            <textarea class="form-control" name="informacion" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
            <label for="floatingTextarea2">Informacion</label>
        </div>
        <br>
        <div class="form-group row">
            <label for="example-date-input" class="col-2 col-form-label">Fecha</label>
            <div class="col-10">
                <input type="date" name="fecha">
            </div>
        </div>
        <br>
        <div class="mb-3">
            <label for="formFile" class="form-label">Imagen</label>
            <input class="form-control" type="file" id="formFile" name="img">
        </div>
        <input type="submit" value="enviar" class="btn btn-primary">
    </header>

</form>

templates/ListProduct.html
<!--is responsible for bringing the template base.html which contains the top bar of the page-->
{% include 'base.html' %}

<!--template that brings all the products created by the user who is logged in-->
<div class="container py-4">
    <div class="row">
        <div class="col-md-10">
            <h2>Productos</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nombre Producto</th>
                            <th>Precio</th>
                            <th></th>
                            <th>Acciones</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for a in object_list %}
                        <tr>
                          <td>{{forloop.counter}}</td>
                          <td>{{a.nombreProduct}}</td>
                          <td>{{a.precio}}</td>
                          <td>
                            <a href="{% url 'product:ActulizarProducto' a.id %}" class="btn btn-warning btn-xs btn-flat">
                                <i class="fas fa-edit">Actualizar</i>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'product:EliminarProducto' a.id %}" class="btn btn-danger btn-xs btn-flat">
                                <i class="fas fa-edit">eliminar</i>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'product:VerProducto' a.id %}" class="btn btn-primary btn-xs btn-flat">
                                <i class="fas fa-edit">ver</i>
                            </a>
                        </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal" tabindex="-1" role="dialog">
        </div>
    </div>
</div>

templates/base.html
<!--the load static, serves so that all the files css, img, js, etc. can be processed.-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{%static 'css/estilos.css' %}">
</head>
<body>
  <!--top navigation bar-->
    <nav>
      <ul class="menu">
        <li class="logo"><a href="#">{{user.username}}</a></li>
        <li class="item"><a href="{% url 'product:Descargar' %}">Descargar Excel</a></li>
        <li class="item"><a href="{% url 'product:ListarProductos' %}">Productos</a></li>
        <li class="item"><a href="{% url 'product:CrearProductos' %}">Agregar Productos</a></li>
        <li class="item button secondary"><a href="{% url 'login:logout' %}">Cerar Sesion</a></li>
      </ul>
</nav>
</body>
</html>

templates/eliminar.html
<!--is responsible for bringing the template base.html which contains the top bar of the page-->
{% include 'base.html' %}
<!--window to confirm the removal of a product-->
<div class="container py-4">
    <div class="row">
        <div class="col-md-10">
            <h2>Eliminar Cliente</h2>
            <form action="" method="POST">
                    {% csrf_token %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban">Notificacion</i></h5>
                    ¿Estas seguro de eliminar el registro?
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-flat">
                        <i class="fas fa-times"></i>Si, caeptar
                    </button>
                    <a href="{% url 'product:ListarProductos' %}" class="btn btn-info btn-flat">
                        <i class="fas fa-times"></i>Cancelar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

templates/informacion.html
<!--is responsible for bringing the template base.html which contains the top bar of the page-->
{% include 'base.html' %}

<!--template that serves to bring the list of a single product-->
<div class="col-md-10">
  <h2 style="text-align: center;">Productos</h2>
  <div class="table-responsive" style="text-align: center; margin-left: 10%;">
      <table class="table table-striped">
          <thead>
              <tr>
                  <th>Nombre Producto</th>
                  <th>Precio</th>
                  <th>Informacion</th>
                  <th>Fecha adquisicion</th>
                  <th>imagen</th>
              </tr>
          </thead>
          <tbody>
              {% for a in object_list %}
              <tr>
                <td>{{a.nombreProduct}}</td>
                <td>{{a.precio}}</td>
                <td>{{a.informacion}}</td>
                <td>{{a.fecha_adquisicion}}</td>
                <td><img class="imagenes" src="/media/{{a.imagen}}" alt="" style="width: 50px; height: 40px;"></td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>

templates/login.html
<!--the load static, serves so that all the files css, img, js, etc. can be processed.-->
{% load static %}
<!--login template-->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>“Mini sistema de información: Administración de
      productos”</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/login.css' %}">
  </head>
  <body>
    <div class="login-box">
      <img src="{%static 'img/logo.png' %}" class="avatar" alt="">
      <h1>Login</h1>
      <form method="POST" action="">
        {% csrf_token %}
        {% if form.errors %}
        <div class="login-box2">
          {{form.error_messages.invalid_login}}
        </div>
        {% endif %}
        <!--the fields form." " are the fields of the forms previously created in the forms.py-->
        <!-- USUARIO INPUT -->
        <label for="username">Usuario:</label>
        {{form.username}}
        <!-- CONTRASEÑA INPUT -->
        <label for="password">contraseña:</label>
        {{form.password}}
        <input type="submit" value="Log in" class="btn btn-primary">
        <br>
        <a href="{% url 'login:registrar' %}">registrarse</a>
      </form>
    </div>
  </body>
</html>

templates/registrar.html
<!--the load static, serves so that all the files css, img, js, etc. can be processed.-->
{% load static %}

<!--user registration template-->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Registrarse</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/registrar.css' %}">
    
  </head>
  <body>

    <div class="login-box">
      <img src="{%static 'img/logo.png' %}" class="avatar" alt="">
      <h1>Login</h1>
      <!--the fields form." " are the fields of the forms previously created in the forms.py-->
      <form method="POST" action="">
        {% csrf_token %}
        <!-- USUARIO INPUT -->
        <label for="username">Username *:</label>
        {{form.username}}
        {% if form.errors.username %}
          <div class="login-box3">
            {{form.errors.username}}
          </div>
        {% endif %}
        <!-- NOMBRE INPUT -->
        <label for="username">Nombres *:</label>
        {{form.first_name}}
        <!-- APELLIDO INPUT -->
        <label for="username">Apellidos *:</label>
        {{form.last_name}}
        <!-- CORREO INPUT -->
        <label for="username">Correo *:</label>
        {{form.email}}
        <!-- CONTRASEÑA INPUT -->
        <label for="username">Contraseña *:</label>
        {{form.password1}}
        <!-- CONFIRMAR CONTRASEÑA INPUT -->
        <label for="password">Confirmar contraseña *:</label>
        {{form.password2}}
        {% if form.errors.password2 %}
          <div class="login-box2">
            {{form.errors.password2}}
          </div>
        {% endif %}
        
        <input type="submit" value="registrar" class="btn btn-primary">
        <br>
        <a href="{% url 'login:login' %}">ya tengo una cuenta</a>
      </form>
    </div>
  </body>
</html>